
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


url=jdbc:sqlserver://localhost:1433;databaseName=TTGShop8;encrypt=false;trustServerCertificate=true
userID=sa
password=123